# Generated by Django 4.0.5 on 2022-06-24 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('Description', models.TextField(verbose_name='مشخصات')),
                ('Image', models.ImageField(upload_to='Images', verbose_name='تصویر')),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('Status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], max_length=1, verbose_name='وضعیت انتشار')),
                ('Published', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
