# Generated by Django 4.0.5 on 2022-07-26 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('Status', models.BooleanField(default=True, verbose_name='تیک وضعیت')),
                ('Position', models.IntegerField(unique=True, verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['Position'],
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('Description', models.TextField(verbose_name='مشخصات')),
                ('Image', models.ImageField(upload_to='Images', verbose_name='تصویر')),
                ('Slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس')),
                ('Status', models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیشنویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت انتشار')),
                ('Published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Is_Special', models.BooleanField(default=False, verbose_name='پست ویژه')),
                ('Category', models.ManyToManyField(to='Nasa.postcategory', verbose_name='دسته بندی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
