# Generated by Django 4.0.5 on 2022-06-29 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('Slug', models.SlugField(max_length=100, unique=True)),
                ('Status', models.BooleanField(default=True, verbose_name='تیک وضعیت')),
                ('Position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['Position'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterField(
            model_name='post',
            name='Published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
