# Generated by Django 4.0.5 on 2022-06-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nasa', '0002_postcategory_alter_post_options_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='Position',
            field=models.IntegerField(unique=True, verbose_name='پوزیشن'),
        ),
    ]
