# Generated by Django 4.0.5 on 2022-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nasa', '0003_alter_postcategory_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.ManyToManyField(to='Nasa.postcategory', verbose_name='دسته بندی'),
        ),
    ]
