# Generated by Django 4.0.4 on 2022-07-19 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nasa', '0006_post_is_special_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس'),
        ),
    ]
